spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery_management
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none    # Không tự động tạo bảng (production), nên dùng Flyway hoặc Liquibase
    show-sql: false     # Tắt log SQL (bảo mật và performance)
    properties:
      hibernate:
        format_sql: false  # Không cần định dạng SQL trong môi trường production

server:
  address: 0.0.0.0
  port: 18080